spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://skyscanner-rds.ctoc0cue8l22.ap-northeast-2.rds.amazonaws.com/skyscanner
    username: admin
    password: admin-password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
