spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test3.ctoc0cue8l22.ap-northeast-2.rds.amazonaws.com:5432/testdb
    username: master
    password: master-password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
