name: Java CD with Gradle

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # JDK 설정
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # application.yml 생성 및 디렉토리 생성
      - run: mkdir -p ./src/main/resources
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run: cat ./src/main/resources/application.yml  # 내용 확인

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          else
            echo "gradlew file not found!"
            exit 1
          fi

      # Gradle Build (test 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # EC2 인스턴스 접속 및 애플리케이션 실행
      - name: Deploy to Hosts
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.BASTION_IP}}  # Bastion Host의 IP 주소 또는 호스트 이름
          username: ${{ secrets.EC2_USERNAME}}  # Bastion Host의 사용자 이름
          key: ${{ secrets.EC2_KEY}}  # Bastion Host의 SSH 개인 키

          script: |
            # EC2에서 작업 디렉터리로 이동
            cd /home/ubuntu/skyscanner-sopt35

            # 최신 코드 가져오기
            sudo git pull origin main
            
            # Gradle 실행 권한 부여
            chmod +x ./gradlew

            # 빌드 실행
            ./gradlew clean build -x test
            
            echo "Stopping any application using port 8080..."
            # 8080 포트를 사용하는 프로세스 찾기
            pid=$(sudo lsof -t -i :8080)
            
            # PID가 존재하는 경우에만 종료
            if [ -n "$pid" ]; then
                echo "Killing process with PID $pid..."
                sudo kill -9 $pid
            else
                echo "No process found using port 8080."
            fi

            # 새 프로세스를 백그라운드에서 실행
            echo "Starting new application in the background..."
            nohup java -jar /home/ubuntu/skyscanner-sopt35/build/libs/skyscanner-0.0.1-SNAPSHOT.jar > /home/ubuntu/skyscanner-sopt35/skyscanner.log 2>&1 &

      
